In [1]:
import os
import numpy as np

import torch
from PIL import Image as IMG

In [2]:
os.chdir('/home/saeid/tracknet/ature')

In [3]:
from commons.MAT import Mat

In [4]:
file = Mat(mat_file='data/DRIVE/mats/gt_drive_test_graph_01.mat')

In [5]:
V = file.get_graph('V')
A = file.get_graph('A')
I = file.get_image('I')

In [6]:
np.where(A[1,:]==1)

(array([   0, 1139]),)

In [7]:
A.shape

(2419, 2419)

In [8]:
path_index = file.get_graph('pathNode')

In [9]:
root = file.get_graph('root')

In [10]:
root

array([[2359]], dtype=uint16)

In [11]:
root_loc = V[root, :]

In [12]:
root_loc

array([[[ 87.33955659, 264.13477246]]])

In [13]:
path_index.shape

(2419, 1)

In [14]:
vessel_pathidx = np.where(path_index==1)[0]

In [15]:
vessel_pathidx.shape

(2187,)

In [16]:
u_pos_input = V[vessel_pathidx, :]

In [17]:
u_pos_input.shape

(2187, 2)

In [18]:
b = np.where(A[vessel_pathidx, :])[0] 

In [19]:
b.shape

(2187,)

In [20]:
b_pos_output = V[b, :]

In [21]:
b_pos_output.shape

(2187, 2)

In [22]:
u_pos_input = u_pos_input.astype(np.int)
b_pos_output = b_pos_output.astype(np.int)

In [40]:
loss1 = torch.dist(torch.FloatTensor(b_pos_output), torch.FloatTensor(u_pos_input), p=2)

In [42]:
loss1/u_pos_input.size

tensor(2.6731)

IndexError: too many indices for tensor of dimension 0

In [43]:
diff = (b_pos_output - u_pos_input)

In [50]:
loss1

tensor(11691.9238)

In [45]:
print(diff[0:100])

[[   0    0]
 [   1   -3]
 [   0   -3]
 [   2   -3]
 [   4   -5]
 [   3   -4]
 [   4   -4]
 [   5   -4]
 [   5   -4]
 [  19  -34]
 [   2   -5]
 [   3   -2]
 [   6  -10]
 [   4   -8]
 [   6  -16]
 [  28  -26]
 [  30  -23]
 [  33  -20]
 [  34  -19]
 [  26  -10]
 [  23  -13]
 [  21  -12]
 [  19  -15]
 [  16  -19]
 [  15  -19]
 [  10  -19]
 [   8  -22]
 [   5  -22]
 [   7  -23]
 [-257 -246]
 [-255 -241]
 [-253 -235]
 [-252 -227]
 [-249 -221]
 [-249 -216]
 [-247 -207]
 [  27   22]
 [  24   23]
 [  26   23]
 [  26   23]
 [  27   22]
 [  28   21]
 [  28   18]
 [  28   18]
 [  26   14]
 [  26   13]
 [  27   10]
 [  27    7]
 [  27    5]
 [  27    3]
 [  30    3]
 [  30    5]
 [  29    7]
 [  29    9]
 [  29   12]
 [  29   15]
 [  29   18]
 [  29   20]
 [  29   21]
 [  29   23]
 [  34   24]
 [  32   27]
 [  31   27]
 [  28   28]
 [  25   28]
 [  22   28]
 [  18   28]
 [  13   30]
 [   8   32]
 [   3   34]
 [  -3   37]
 [  -8   37]
 [  -4   34]
 [  -2   33]
 [   3   37]
 [   5   38]
 [   6   39]

In [ ]:
IMG.fromarray(img.astype(np.uint8))

In [27]:
for i in range(len(u_pos_input)):
    print(u_pos_input[i], b_pos_output[i], ' DIff: ', b_pos_output[i]-u_pos_input[i])

[141 165] [141 165]  DIff:  [0 0]
[140 171] [141 168]  DIff:  [ 1 -3]
[140 174] [140 171]  DIff:  [ 0 -3]
[138 177] [140 174]  DIff:  [ 2 -3]
[134 182] [138 177]  DIff:  [ 4 -5]
[131 186] [134 182]  DIff:  [ 3 -4]
[127 190] [131 186]  DIff:  [ 4 -4]
[122 194] [127 190]  DIff:  [ 5 -4]
[117 198] [122 194]  DIff:  [ 5 -4]
[ 98 232] [117 198]  DIff:  [ 19 -34]
[ 96 237] [ 98 232]  DIff:  [ 2 -5]
[ 93 239] [ 96 237]  DIff:  [ 3 -2]
[ 87 249] [ 93 239]  DIff:  [  6 -10]
[ 83 257] [ 87 249]  DIff:  [ 4 -8]
[ 79 268] [ 85 252]  DIff:  [  6 -16]
[ 55 283] [ 83 257]  DIff:  [ 28 -26]
[ 52 283] [ 82 260]  DIff:  [ 30 -23]
[ 47 284] [ 80 264]  DIff:  [ 33 -20]
[ 45 287] [ 79 268]  DIff:  [ 34 -19]
[ 40 290] [ 66 280]  DIff:  [ 26 -10]
[ 37 292] [ 60 279]  DIff:  [ 23 -13]
[ 34 295] [ 55 283]  DIff:  [ 21 -12]
[ 33 298] [ 52 283]  DIff:  [ 19 -15]
[ 31 303] [ 47 284]  DIff:  [ 16 -19]
[ 30 306] [ 45 287]  DIff:  [ 15 -19]
[ 30 309] [ 40 290]  DIff:  [ 10 -19]
[ 29 314] [ 37 292]  DIff:  [  8 -22]


[279 231] [297 483]  DIff:  [ 18 252]
[287 229] [136 395]  DIff:  [-151  166]
[290 229] [137 398]  DIff:  [-153  169]
[293 228] [139 403]  DIff:  [-154  175]
[296 228] [140 406]  DIff:  [-156  178]
[299 228] [143 411]  DIff:  [-156  183]
[302 227] [148 416]  DIff:  [-154  189]
[305 226] [151 417]  DIff:  [-154  191]
[309 224] [154 418]  DIff:  [-155  194]
[312 223] [158 420]  DIff:  [-154  197]
[315 223] [161 421]  DIff:  [-154  198]
[318 223] [164 422]  DIff:  [-154  199]
[321 223] [169 423]  DIff:  [-152  200]
[324 223] [104 228]  DIff:  [-220    5]
[328 224] [109 229]  DIff:  [-219    5]
[332 225] [112 230]  DIff:  [-220    5]
[335 225] [117 230]  DIff:  [-218    5]
[346 222] [121 229]  DIff:  [-225    7]
[349 220] [124 228]  DIff:  [-225    8]
[351 217] [129 225]  DIff:  [-222    8]
[356 212] [134 224]  DIff:  [-222   12]
[359 211] [139 219]  DIff:  [-220    8]
[362 211] [144 216]  DIff:  [-218    5]
[365 212] [147 215]  DIff:  [-218    3]
[371 210] [150 214]  DIff:  [-221    4]
[3

[396 248] [394 372]  DIff:  [ -2 124]
[398 245] [391 376]  DIff:  [ -7 131]
[405 237] [389 379]  DIff:  [-16 142]
[408 235] [387 382]  DIff:  [-21 147]
[414 229] [382 386]  DIff:  [-32 157]
[416 226] [378 389]  DIff:  [-38 163]
[418 223] [375 391]  DIff:  [-43 168]
[420 220] [372 393]  DIff:  [-48 173]
[422 217] [369 395]  DIff:  [-53 178]
[424 214] [366 398]  DIff:  [-58 184]
[423 211] [363 400]  DIff:  [-60 189]
[423 206] [360 401]  DIff:  [-63 195]
[423 201] [357 403]  DIff:  [-66 202]
[422 505] [354 406]  DIff:  [-68 -99]
[424 508] [351 407]  DIff:  [ -73 -101]
[425 511] [348 409]  DIff:  [ -77 -102]
[426 514] [345 411]  DIff:  [ -81 -103]
[427 517] [342 412]  DIff:  [ -85 -105]
[515 178] [339 412]  DIff:  [-176  234]
[512 178] [336 412]  DIff:  [-176  234]
[508 179] [333 412]  DIff:  [-175  233]
[503 179] [330 412]  DIff:  [-173  233]
[500 180] [327 412]  DIff:  [-173  232]
[497 180] [324 414]  DIff:  [-173  234]
[494 180] [319 415]  DIff:  [-175  235]
[491 180] [314 415]  DIff:  

[349 233] [176 297]  DIff:  [-173   64]
[351 236] [171 156]  DIff:  [-180  -80]
[352 239] [173 160]  DIff:  [-179  -79]
[353 242] [174 163]  DIff:  [-179  -79]
[354 245] [177 164]  DIff:  [-177  -81]
[355 248] [180 166]  DIff:  [-175  -82]
[355 254] [183 167]  DIff:  [-172  -87]
[354 258] [186 167]  DIff:  [-168  -91]
[356  68] [190 407]  DIff:  [-166  339]
[353  69] [193 402]  DIff:  [-160  333]
[351  72] [195 398]  DIff:  [-156  326]
[351  75] [201 278]  DIff:  [-150  203]
[360 251] [204 279]  DIff:  [-156   28]
[363 251] [209 282]  DIff:  [-154   31]
[366 251] [212 284]  DIff:  [-154   33]
[369 252] [213 287]  DIff:  [-156   35]
[372 253] [216 289]  DIff:  [-156   36]
[366 456] [197  77]  DIff:  [-169 -379]
[369 456] [202  82]  DIff:  [-167 -374]
[372 457] [203  85]  DIff:  [-169 -372]
[375 458] [203  88]  DIff:  [-172 -370]
[378 458] [204  91]  DIff:  [-174 -367]
[381 460] [204  94]  DIff:  [-177 -366]
[364 352] [203  99]  DIff:  [-161 -253]
[367 352] [204 228]  DIff:  [-163 -124]


In [51]:
IMG.fromarray(img.astype(np.uint8))

NameError: name 'img' is not defined

In [29]:
x=np.where(path_index==1)[0]

In [30]:
input_pos = np.where(A==1)[1]

In [31]:
A.shape

(2419, 2419)

In [32]:
all_inputs = V[input_pos,:]

In [33]:
b = np.where(A[input_pos, :])[0]
output_pos = V[b, :]

In [34]:
all_inputs - output_pos

ValueError: operands could not be broadcast together with shapes (2418,2) (2415,2) 

In [35]:
outputs-inputs

NameError: name 'outputs' is not defined

In [36]:

for i in range(len(inputs)):
    print(inputs[i], outputs[i], ' DIff: ', outputs[i]-inputs[i])

NameError: name 'inputs' is not defined

In [37]:
IMG.fromarray(img.astype(np.uint8))

NameError: name 'img' is not defined